---
title: "colocalization"
author: "chj1ar"
date: "2019-08-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

This part is based on the paper 'Integrating molecular QTL data into genome-wide genetic association analysis: Probabilistic assessment of enrichment and colocalization' with the software Enloc.

## Background

The roles of GWAS in disease etiology remain poorly understood. Linking molecular QTLs to GWAS is important to interpret the biological relevance of GWAS results. Colocalizing genetic variants that jointly affect both molecular and organismal phenotypes provides a starting point for exploring the role of genetic variants in disease etiology. We therefore perform colocalization analysis of eQTLs from different tissues and schizophrenia (SCZ) GWAS to identify genes in specific tissues which play an important role in molecular pathways of complex traits. Specifically, we perform enrichment analysis, GWAS fine-mapping, and colocalization analysis. The enrichment analysis aims to estimate the enrichment level of eQTL to GWAS, and so the GWAS fine-mapping can be more accurate with eQTL information and the enrichment estimation. The colocalization analysis is aided by both the enrichment estimation and the GWAS fine-mapping results.

## Methods

For the basic framework, we use a multiple linear regression model to describe the associations of a quantitative trait with p candidate SNPs and n unrelated samples, i.e., $y = \sum_{i=1}^{p} \beta_i g_i + e$, and we will obtain $\beta_i$, the genetic effect of each SNP to the quantitative trait, and $\gamma_i$, the binary causal state of each SNP, by dichotomizing its genetic effect, i.e., $\gamma_i=\begin{cases}1, &\beta_i \neq 0 \cr 0, &otherwise\end{cases}$. The $\gamma_i$ will be used to identify colocalized SNPs, i.e., the SNPs that are causal to both the quantitative trait and some tissue-specific gene expression.

We perform the enrichment analysis by integrating the SNP-level annotation into the association analysis by specifying a natural logistic prior for each candidate SNP. Here, we consider a special setting in which the SNP-level annotation is derived from the association status of eQTL data, and the formula is $log \frac {P(\gamma_i = 1)}{P(\gamma_i = 0)} = \alpha_0 + \alpha_1 d_i$. Unfortunately, precise binary association status of each SNP with respect to tissue-specific gene expression is practically impossible to obtain. As a consequence, there is considerable uncertainty in the SNP-level annotation. We therefore use the posterior distribution $P(d | Y_{qtl}, G_{qtl})$ to describe the uncertainty, and $d_i$ can be sampled from $P(d_i | Y_{qtl}, G_{qtl})$.

To be specific, the posterior distribution of d is derived from individual-level genotype-expression data by QTL fine-mapping. Then, there are dozens of annotations, i.e., d, sampled from the posterior distribution of d, and for each sampled annotation, the enrichment analysis stated above will be performed to generate their respective results of log odds ratio, 95% CI, etc.. The final result is generated by taking the average of the respective results of sampled annotations. In theory, it can be shown that this scheme, the so-called 'multiple imputation', is way better than directly using eQTL PIPs, the posterior distributions of d's, i.e., the so-called 'mean imputation'.

For prior specification, instead of specifying $p_1 := P(\gamma_i = 1, d_i = 0)$, $p_2 := P(\gamma_i = 0, d_i = 1)$ and $p_{12} := P(\gamma_i = 1, d_i = 1)$, as commonly used, we equivalently parameterize them by specifying

$$\alpha_0 = log \frac {p_1}{1 - p_1 - p_2 - p_{12}}$$

$$\alpha_1 = log \frac {p_{12} (1 - p_1 - p_2 - p_{12})}{p_1 p_2}$$

Plus, $\alpha_1$ is learned by whole-genome SNPs, with the idea of empirical Bayes.

## Input

Molecular QTL data, GWAS data (specifically, QTL configurations and GWAS summary association statistics)

## Output

enrichment estimation, GWAS PIP, colocalization probabilities

## Results

Before showing the results on SCZ, it'd be better to show the correctness of the pipeline by reproducing the Figure 5 of the Enloc paper. Specifically, we performed enrichment analysis of GTEx Whole Blood eQTLs data on 4 lipid traits, namely, high density lipoprotein (HDL), low density lipoprotein (LDL), triglycerides (TG), and total cholesterol (TC), and the following figure, Figure 1, shows the results.

```{r, echo=FALSE}
library(png)
lipid_traits <- readPNG(source = '~/Documents/留学/暑研/Xin/reading_materials/5th/lipid_traits_Enloc.png')
library(grid)
grid.raster(lipid_traits)
```


There is little difference from the Figure 5 of the Enloc paper, demonstrating that the pipeline should be correct.

Time limited, we failed to get the results for SCZ.
