---
title: "Enrichment and Colocalization"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This project consists of two parts, enrichment analysis and colocalization analysis. Enrichment analysis is performed on 44 tissues of eQTL in GTEx in 2 ways. One is performed in binary annotations, and the other is in PIPs, i.e., continuous annotations. Then, there should be diagnosis of enrichment analysis by QQ plots if there are too few eQTL SNPs. After that, we use Enloc to perform enrichment estimation aided colocalization analysis, but first we need to prepare necessary data.

Please find the details as follows.

* [SCZ against binary annotations of GTEx eQTLs](binary.html)

* [SCZ against PIPs of GTEx eQTLs](PIP.html)

* [diagnosis of enrichment analysis by QQ plots](diagnosis_QQplot.html)

* [colocalization analysis of brain eQTLs on SCZ by Enloc](colocalization.html)

* [generating individual-level genotype-expression data](https://github.com/chj1ar/fine-mapping/)

If you are interested in the code, please find it in [`code/`](https://github.com/chj1ar/weekly_report20190715-21/tree/master/code/).
